### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by Daf98** [gvgesanto2/microverse-portfolio-mobile#11]
Very well organized and clean code. Some suggestions:

- Kindly fix the spelling of the word "hamburger" on some of your JavaScript functions and objects
[OPTIONAL] We kindly suggest using `article` or `section` elements instead of `div` elements

Happy coding 🎊

**Comment by gvgesanto2** [comment]
## Hi 👋,

Thanks for the feedback! I've just fixed these issues in my last pull request, as suggested.
**Pull Request**: https://github.com/gvgesanto2/microverse-portfolio-mobile/pull/12.
